pizza_delivery/backend/authen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('register/otp-gen/', views.registerOtpGen, name="otp_gen"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    path('forget-pass/', views.forgotPassPage, name="forget_pass"),
    path('forget-pass/otp-gen/', views.forgotOtpGen, name="forgot_otp_gen"),
    path('change-pass/', views.changePassPage, name="change_pass"),
]

pizza_delivery/backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("authen.urls")),
    path('', include("pizzaDelivery.urls")),
]

pizza_delivery/backend/pizzaDelivery/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('profile/', views.profilePage, name="profile"),
    path('profile/update-profile/', views.updateProfile, name="update_profile"),
    path('pizza/buy/', views.pizzaBuy, name="buy_pizza"),
    path('pizza/buy/payment-initiator/', views.paymentInitiator, name="payment_initiator"),
    path('pizza/buy/paymenthandler/', views.paymentHandler, name="payment-handler"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizza_delivery/backend/pizzaDelivery/models.py
from django.db import models
from django.conf import settings
from django.utils.safestring import mark_safe


class PizzaBase(models.Model):
    name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    
    def __str__(self) -> str:
        return self.name

class PizzaSauce(models.Model):
    name = models.CharField(max_length=255)
    is_available = models.BooleanField(default=True, null=False)
    
    def __str__(self) -> str:
        return self.name

class PizzaCheese(models.Model):
    name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    
    def __str__(self) -> str:
        return self.name

class PizzaVeggie(models.Model):
    name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    
    def __str__(self) -> str:
        return self.name
   

class Pizza(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, unique=True)
    decription = models.TextField(null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=False, blank=False)
    image = models.ImageField(upload_to='pizza_images/', null=True, blank=True)
    pizza_base = models.ForeignKey(PizzaBase, on_delete=models.PROTECT, related_name="pizza_b")
    pizza_sauce = models.ManyToManyField(PizzaSauce, related_name="pizza_s")
    pizza_cheese = models.ForeignKey(PizzaCheese, on_delete=models.PROTECT, related_name="pizza_c")
    pizza_veggie = models.ManyToManyField(PizzaVeggie, related_name="pizza_v")
    custom = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address_line1 = models.TextField()
    address_line2 = models.TextField()
    pincode = models.CharField(max_length=6, default="")
    city = models.CharField(max_length=255, null=True, default="")
    state = models.CharField(max_length=255, null=True, default="")
    country = models.CharField(max_length=255, null=True, default="")

    def __str__(self) -> str:
        return self.user.first_name + " " + self.user.last_name
    

class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ("R", "Order Recieved"),
        ("I", "In the Kithen"),
        ("O", "Out for Delivery"),
        ("D", "Delevered")
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order_status = models.CharField(max_length=255, choices=ORDER_STATUS_CHOICES, null=True)
    payment_status = models.CharField(max_length=255)
    razorpay_order_id = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self) -> str:
        return self.customer.user.first_name + ' ' + self.customer.user.last_name + ' ' + str(self.id)

class OrderItem(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.PROTECT)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    quantity = models.PositiveIntegerField(default=1)

pizza_delivery/backend/pizzaDelivery/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseBadRequest
from django.db import transaction
from django.db.utils import IntegrityError
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import razorpay
import json
from .models import Pizza, OrderItem, Order, Customer, PizzaVeggie, PizzaSauce, PizzaBase, PizzaCheese

razorpay_client = razorpay.Client(
    auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))

def dashboard(request):
    if request.method == "POST":
        pizza_name = json.loads(request.body).get("pizza_name")
        pizza_base = json.loads(request.body).get("pizza_base")
        pizza_cheese = json.loads(request.body).get("pizza_cheese")
        pizza_veggies = json.loads(request.body).get("pizza_veggies")
        pizza_sauces = json.loads(request.body).get("pizza_sauces")
        price = 300

        if pizza_name != "":
            try:
                new_pizza = Pizza.objects.create(name = pizza_name, price = price, 
                                                pizza_base=PizzaBase.objects.get(id=pizza_base), 
                                                pizza_cheese=PizzaCheese.objects.get(id=pizza_cheese), 
                                                custom = True)
                if pizza_veggies:
                    new_pizza.pizza_veggie.set(PizzaVeggie.objects.filter(id__in = pizza_veggies))
                if pizza_sauces:
                    new_pizza.pizza_sauce.set(PizzaSauce.objects.filter(id__in = pizza_sauces))
                new_pizza.save()
                return JsonResponse({"message":"You can now order your custom pizza", "order":1, "pizza_id": str(new_pizza.id)})
            except:
                return JsonResponse({"message":"Please select another pizza name.", "order":0})

    pizza_list = Pizza.objects.filter(custom = False)
    bases = PizzaBase.objects.filter(quantity__gt =0)
    cheeses = PizzaCheese.objects.filter(quantity__gt = 0)
    veggies = PizzaVeggie.objects.filter(quantity__gt = 0)
    sauces = PizzaSauce.objects.filter(is_available = True)
    return render(request, 'dashboard.html', context={"pizzas":pizza_list, 
                                                      "bases":bases, 
                                                      "cheeses":cheeses, 
                                                      "veggies": veggies, 
                                                      "sauces":sauces})

@login_required(login_url="login")
def pizzaBuy(request):
    if request.method == "POST":
        curr_user = request.user
        pizza_id = request.POST.get("pizza_id")

        customer_obj, exist = Customer.objects.get_or_create(user = curr_user)
        customer_obj.save()

        pizza_obj = Pizza.objects.get(id = pizza_id)
        veggies = PizzaVeggie.objects.prefetch_related("pizza_v").filter(pizza_v = pizza_id)
        sauces = PizzaSauce.objects.prefetch_related("pizza_s").filter(pizza_s = pizza_id)

        return render(request, "buyPage.html", {"customer": customer_obj, "pizza":pizza_obj, "pizza_veggies":veggies, "pizza_sauces":sauces})
    return redirect("dashboard")


def paymentInitiator(request):
    if request.method == "POST":
        currency = 'INR'

        curr_user = request.user
        pizza_id = json.loads(request.body).get("pizza_id")
        quantity = json.loads(request.body).get("quantity")

        pizza_obj = Pizza.objects.get(id = int(pizza_id))
        amount = int(pizza_obj.price) * 100 * int(quantity)

        customer_obj, exist = Customer.objects.get_or_create(user = curr_user)
        customer_obj.save()


        razorpay_order = razorpay_client.order.create(dict(amount=amount,
                                                       currency=currency,
                                                       payment_capture='0'))
        
        razorpay_order_id = razorpay_order['id']
        callback_url = 'paymenthandler/'

        with transaction.atomic():
            order_obj = Order.objects.create(customer = customer_obj, payment_status = "pending",order_status="C", razorpay_order_id=razorpay_order_id, amount=(amount/100))
            order_obj.save()

            order_item_obj = OrderItem.objects.create(pizza = pizza_obj, order = order_obj, quantity = quantity)
            order_item_obj.save()

        context = {}
        context['razorpay_order_id'] = razorpay_order_id
        context['razorpay_merchant_key'] = settings.RAZOR_KEY_ID
        context['razorpay_amount'] = amount
        context['currency'] = currency
        context['callback_url'] = callback_url

        return JsonResponse(context)

@csrf_exempt
def paymentHandler(request):
    if request.method == "POST":
        try:
            payment_id = request.POST.get('razorpay_payment_id', '')
            razorpay_order_id = request.POST.get('razorpay_order_id', '')
            signature = request.POST.get('razorpay_signature', '')
            params_dict = {
                'razorpay_order_id': razorpay_order_id,
                'razorpay_payment_id': payment_id,
                'razorpay_signature': signature
            }

            order_obj = Order.objects.get(razorpay_order_id = razorpay_order_id)

            result = razorpay_client.utility.verify_payment_signature(params_dict)
            
            if result is not None:
                amount = int(order_obj.amount) * 100
                
                try:

                    razorpay_client.payment.capture(payment_id, amount)
                    order_obj.payment_status = "successfull"
                    order_obj.order_status = "R"
                    order_obj.save()
                    try:
                        order_items = order_obj.orderitems.all()
                        for item in order_items:
                            base = item.pizza.pizza_base
                            base.quantity -= item.quantity
                            base.save()

                            cheese = item.pizza.pizza_cheese
                            cheese.quantity -= item.quantity
                            cheese.save()

                            veggies = item.pizza.pizza_veggie.all()
                            for veggie in veggies:
                                veggie.quantity -= item.quantity
                                veggie.save()
                            
                    except BaseException as e:
                        print(e)

                    return render(request, 'message1.html', {"heading": "Payment Successfull", "message": "your payment is successfull.", "button":"View Order"})
                except:
                    order_obj.delete()
                    return render(request, 'message.html', {"heading": "Payment Failed", "message": "your payment is unsuccessfull.", "button":"View Order"})
            else:
                order_obj.delete()
                return render(request, 'message.html', {"heading": "Payment Failed", "message": "your payment is unsuccessfull.", "button":"View Order"})

        except:
            return HttpResponseBadRequest()
    else:
        return HttpResponseBadRequest()

@login_required(login_url="login")
def profilePage(request):
    if request.method == "GET":
        curr_user = request.user
        curr_customer, exist = Customer.objects.get_or_create(user = curr_user)

        orders = Order.objects.prefetch_related("orderitems").filter(customer = curr_customer).filter(payment_status = "successfull")
        return render(request, "profile.html", {"customer": curr_customer, "orders":orders})
    return HttpResponseBadRequest()

@login_required(login_url="login")    
def updateProfile(request):
    if request.method ==  "POST":
        try:
            first_name = json.loads(request.body).get("first_name")
            last_name = json.loads(request.body).get("last_name")
            add_l1 = json.loads(request.body).get("add_l1")
            add_l2 = json.loads(request.body).get("add_l2")
            pincode = json.loads(request.body).get("pincode")
            city = json.loads(request.body).get("city")
            state = json.loads(request.body).get("state")
            country = json.loads(request.body).get("country")

            curr_user = request.user
            if first_name:
                curr_user.first_name = first_name
                curr_user.last_name = last_name
                curr_user.save()

            curr_customer = Customer.objects.get(user = curr_user)
            curr_customer.address_line1 = add_l1
            curr_customer.address_line2 = add_l2
            curr_customer.pincode = pincode
            curr_customer.city = city
            curr_customer.state = state
            curr_customer.country = country
            curr_customer.save()
            
            return JsonResponse("Profile updated successfully", safe=False)
        except IntegrityError as e:
            print(e)
            return JsonResponse("Profile updation failed. May be due to an empty field.", safe=False)

    return HttpResponseBadRequest()

pizza_delivery/backend/pizzaDelivery/templates/message.html
<!DOCTYPE html>
<html>
<head>
    <title>Response</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        
        .container {
            max-width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        h2 {
            text-align: center;
            color: #333;
        }
        
        .text {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }
        
        button {
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            border: none;
            color: #fff;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>{{ heading }}</h2>
        <p class="text">{{ message }}</p>
        <button onclick="window.location.replace("{% url 'profile' %}");">{{ button }}</button>
    </div>
</body>
</html>

pizza_delivery/backend/pizzaDelivery/templates/message1.html
<!DOCTYPE html>
<html>
<head>
    <title>Response</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        
        .container {
            max-width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        h2 {
            text-align: center;
            color: #333;
        }
        
        .text {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }
        
        button {
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            border: none;
            color: #fff;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>{{ heading }}</h2>
        <p class="text">{{ message }}</p>
        <button onclick=window.location.replace("{% url 'profile' %}");>{{ button }}</button>
    </div>
</body>
</html>

pizza_delivery/backend/pizzaDelivery/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        header {
            background-color: #333;
            color: white;
            padding: 1em;
            text-align: center;
        }

        nav {
            display: flex;
            align-items: center;
            background-color: #444;
            color: white;
            padding: 0.5em;
            text-align: center;
        }

        nav ul {
            flex: 10% 1 1 1;
            flex-wrap: wrap;
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
        }

        nav ul li {
            margin: 0 1em;
        }

        nav ul li a {
            color: white;
            text-decoration: none;
            font-weight: bold;
        }

        nav ul li a:hover {
            text-decoration: underline;
        }

        .container {
            display: block;
            margin: 20px;
            padding: 5px;
            border: 2px solid grey;
            border-radius: 20px;
            background-color: #fff;
        }

        table {
            display: inline;
            margin: 1px;
            padding: 1px;
            font-size: 16px;
            height: 1px;
            width: 50%;
        }
        .editable {
            border-radius: 2px;
            background-color: rgb(241, 239, 239);
        }

        input[type="button"] {
            width: 200px;
            height: 50px;
            margin-top: 10px;
            margin-bottom: 10px;
            background-color: #24a0ed;
            border: none;
            border-radius: 5px;
            color: #fff;
            cursor: pointer;
            font-size: 16px;
            transition: background-color .5s;
        }

        input[type="button"]:hover {
            background-color: #0086d0;
        }

        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
        }

        .pizza-item {
            display: flex;
            margin: 10px;
            border: 2px solid black;
            border-radius: 5px;
            height: fit-content;
        }

        .pizza-item-image {
            flex: 30% 2 0;
            margin: 10px;
        }

        #pincode {
            border: none;
            background-color: rgb(241, 239, 239);
            width: 99%;
            height: 100%;
        }
    </style>
</head>

<body>
    <header>
        <h1>Your Profile</h1>
    </header>
    <nav>
        <div style="flex: 1 1 1px; flex-wrap: wrap;"></div>
        <ul>
            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
            {% if user.is_anonymous %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
            {% else %}
            <li><a href="{% url 'profile' %}">Profile</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
        <div style="flex: 1 1 1px; flex-wrap: wrap; text-align: right;"><p>Username: {{ request.user.username }}</p></div>
    </nav>
    <main>
        <div class="container">
            <h1>Your Details</h1>
            <table>
                <tbody>
                    <tr>
                        <td style="width: 50%; align-items: left;">First Name</td>
                        <td style="width: 5%;">:</td>
                        <td class="editable" id="first_name">{{ request.user.first_name }}</td>
                    </tr>
                    <tr>
                        <td>Last Name</td>
                        <td>:</td>
                        <td class="editable" id="last_name">{{ request.user.last_name }}</td>
                    </tr>
                    <tr>
                        <td style="width: 50%; align-items: left;">Address Line 1</td>
                        <td style="width: 5%;">:</td>
                        <td class="editable" id="add_l1">{{ customer.address_line1 }}</td>
                    </tr>
                    <tr>
                        <td>Address Line 2</td>
                        <td>:</td>
                        <td class="editable" id="add_l2">{{ customer.address_line2 }}</td>
                    </tr>
                    <tr>
                        <td>Pincode</td>
                        <td>:</td>
                        <td ><input class="editable" type="number"
                                value="{{ customer.pincode }}" id="pincode" disabled oninput="if(this.value>999999){this.value = this.value.slice(0, 6);}
                                    else if(this.value<0){this.value='0';}">
                        </td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td>:</td>
                        <td class="editable" id="city">{{ customer.city }}</td>
                    </tr>
                    <tr>
                        <td>State</td>
                        <td>:</td>
                        <td class="editable" id="state">{{ customer.state }}</td>
                    </tr>
                    <tr>
                        <td>Country</td>
                        <td>:</td>
                        <td class="editable" id="country">{{ customer.country }}</td>
                    </tr>
                </tbody>
            </table>
            <div style="display: block; margin: 10px;">
                <input id="edit_profile_btn" type="button" value="Edit Details" onclick=makeEditable();>
                <input style="visibility: hidden;" id="update_profile_btn" type="button" value="Update Profile" onclick=updateProfile();>
            </div>
        </div>
        <div class="container">
            <h1>Your Orders</h1>
            {% for order in orders %}
            {% for orderitem in order.orderitems.all %}
            <div class="pizza-item">
                <div class="pizza-item-image">
                    <img src="http://{{ request.get_host }}/{{ orderitem.pizza.image }}" style="border-radius: 5px;" width="100%"
                        height="100%" alt="pizza image">
                </div>
                <div class="pizza-item-details" style="flex: 70%; display: flex; flex-wrap: wrap;">
                    <div class="pizz-item-name" style="flex: 45%;">
                        
                        <h2>{{ orderitem.pizza.name }}</h2>
                        <table>
                            <tbody>
                                <tr style="height: fit-content;">
                                    <td><h3>Quantity</h3></td>
                                    <td>:</td>
                                    <td>{{ orderitem.quantity }}</td>
                                </tr>
                                <tr style="height: fit-content;">
                                    <td><h3>Payment</h3></td>
                                    <td>:</td>
                                    <td>{{ order.payment_status }}</td>
                                </tr>
                                <tr style="height: fit-content;">
                                    <td><h3>Order Status</h3></td>
                                    <td>:</td>
                                    <td>{{ order.get_order_status_display }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="pizza-item-detail" style="flex: 55%;">
                        <table>
                            <tbody>
                                <tr>
                                    <td><h3>Base</h3></td>
                                    <td>:</td>
                                    <td>{{ orderitem.pizza.pizza_base }}</td>
                                </tr>
                                <tr>
                                    <td><h3>Sauce</h3></td>
                                    <td>:</td>
                                    <td class="trip_2_char">{% for sauce in orderitem.pizza.pizza_sauce.all %}, {{ sauce.name }}{% endfor %}a</td>
                                </tr>
                                <tr>
                                    <td><h3>veggies</h3></td>
                                    <td>:</td>
                                    <td class="trip_2_char">{% for veggie in orderitem.pizza.pizza_veggie.all %}, {{ veggie.name }}{% endfor %}</td>
                                </tr>
                                <tr>
                                    <td><h3>Cheese</h3></td>
                                    <td>:</td>
                                    <td>{{ orderitem.pizza.pizza_cheese }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endfor %}
        </div>
    </main>
</body>
<script>
    let flag = false;
    function makeEditable() {
        let btn = document.getElementById("edit_profile_btn");
        if (flag) {
            btn.style.backgroundColor = "#24a0ed";
            flag = false;
        }
        else {
            btn.style.backgroundColor = "#c1c7cb";
            flag = true;
        }
        updateBtnVisibility();

        let elements = document.getElementsByClassName("editable");
        let pincode_input = document.getElementById("pincode");
        for (let i = 0; i < elements.length; i++) {
            if (!flag) {
                elements[i].contentEditable = "false";
                pincode_input.disabled = true;
                elements[i].style.backgroundColor = "rgb(241, 239, 239)";
            }
            else {
                elements[i].contentEditable = "true";
                pincode_input.disabled = false;
                elements[i].style.backgroundColor = "lightgrey";
            }
        }
    }
    
    function updateProfile() {
        let csrf = document.cookie.split("=")[1];
        let first_name = document.getElementById("first_name").innerText;
        let last_name = document.getElementById("last_name").innerText;
        let add_l1 = document.getElementById("add_l1").innerText;
        let add_l2 = document.getElementById("add_l2").innerText;
        let pin = document.getElementById("pincode").value;
        let city = document.getElementById("city").innerText;
        let state = document.getElementById("state").innerText;
        let country = document.getElementById("country").innerText;

        let update_btn = document.getElementById("update_profile_btn");
        update_btn.value = "Updating";

        let x = fetch('update-profile/', {
            method: "POST",
            headers: {
                "X-CSRFToken": csrf,
            },
            body: JSON.stringify({
                "first_name": first_name,
                "last_name": last_name,
                "add_l1": add_l1,
                "add_l2": add_l2,
                "pincode": pin,
                "city": city,
                "state": state,
                "country": country,
            }),
        });
        let data = x.then(r => r.json()).then(u => { return u; });
        const returnData = async () => {
            let d = await data;
            alert(d);
            update_btn.value = "Update Profile";
            makeEditable();
        }
        returnData();
    }

    let elems = document.getElementsByClassName("trip_2_char");
    for(let i=0; i<elems.length; i++){
        elems[i].innerHTML = String(elems[i].innerHTML).substring(2);
    }

    function updateBtnVisibility() {
        let hidden = document.getElementById('update_profile_btn').style.visibility;
        if(hidden === 'visible') {
            document.getElementById('update_profile_btn').style.visibility = 'hidden';
        } else {
            document.getElementById('update_profile_btn').style.visibility = 'visible';
        }
    }

</script>

</html>